### ISSUE TITLE
Picture blur

### ISSUE THREAD

**Issue by wandoubudou** [MACILLAS/UWCNN#1]
i used your method in paper to train a model, but when i test images the result doesn't the same as picture in paper,the picture is too haze to look,and i have no idea what's worng in my model, please help thank you.

**Comment by MACILLAS** [comment]
Hi @wandoubudou 
Can you please provide some additional details? I'm wondering if this might be a training issue, data issue or maybe just mismatch turbidity? 

I guess the first thing I would check is what turbidity of water of the testing image and what turbidity the network is trained to enhance.

I would also direct you to the original authors of UWCNN+ which this code is based on... https://doi.org/10.1016/j.patcog.2019.107038 (the link on readme seems not to work anymore)

**Comment by wandoubudou** [comment]
> 
Thank you for your reply!
I used the type1 in generate_image_underwater_v3.py and i have changed 
horization = 15 - 15.4 * random.uniform(0, 1)  --->horization = 0.

the reason why i changed the horization is that i get the turbidity problem when i first train without change any dataset,i want to fix the problem by changing horization = 0, but i failed, turbidity problem is still there...


after i trained 40 epoch the result like the following pictures. The test result is unacceptable.

![type1_617_img_](https://user-images.githubusercontent.com/37957772/143672482-fb504ed6-e553-4f62-ac78-ecb09cb94ea5.png)
![617_img_](https://user-images.githubusercontent.com/37957772/143672497-9c70f417-99fd-4358-9e22-434b87e86db3.png)

What's more, when i trained the network the minimum value of loss is 0.38, is that mean the network training is failed?

**Comment by MACILLAS** [comment]
I think that might be your issue... That code you are referring to is from Li et. al 2020 so you'll have to check with them why they choose to do this. 

Have you had a look at the training images that your modification generates? I think what happening is when horizon = 0 the images are much more corrupted; and the CNN is having difficulty learning to enhance the images.

**Comment by wandoubudou** [comment]
> 
I didn't change the code at first, i let horization = 15 - 15.4 * random.uniform(0, 1) initial, which means i didn't change anything,but the result is just like the image i mentioned, then i think is that the problem of the generated under water images, so i change horizon = 0, but problem doesn't fixed...
i checked the generate underwater images, when horizon = 0 the image is just blue not turbid.
ummm, i think is my training issue, so where can i change the turbidity in training? i didn't find any code about that, need your help, pretty please.

**Comment by wandoubudou** [comment]
ummm, i think it is my problem. i am a fool, 

Firstly, i try to train the network, and i got a error is the GT image and UW image size didn't match, so i just reshape the GT image, so i got a bad model.

 now i know i need to reshape image in preprocess.py, then the problem fixed.

**Comment by MACILLAS** [comment]
Oh okay. Thanks for letting me know. Yeah I should of made a pipeline where I automatically resize the images... 

Closing Issue.
